[build]
  command = "npm run generate"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "24.20.0"

[[redirects]]
from = "https://michaelborn.me/*"
to = "https://www.michaelborn.me/:splat"
status = 301
